apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-service-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  Migrations__ApplyOnStartup: "true"
  RabbitMq__Host: rabbitmq
  RabbitMq__Port: "5672"
  RabbitMq__VirtualHost: /
  UsersService__BaseUrl: http://users-service:8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: users-service-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  Migrations__ApplyOnStartup: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  Migrations__ApplyOnStartup: "true"
  RabbitMq__Host: rabbitmq
  RabbitMq__Port: "5672"
  RabbitMq__VirtualHost: /
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-service-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:8080
  Migrations__ApplyOnStartup: "true"
  CoreService__BaseUrl: http://core-service:8080
  UsersService__BaseUrl: http://users-service:8080
