apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: admin
  RabbitMq__Username: admin
  RabbitMq__Password: admin
  ConnectionStrings__CoreDb: Host=core-db;Port=5432;Database=core;Username=postgres;Password=postgres
  ConnectionStrings__UsersDb: Host=users-db;Port=5432;Database=users;Username=postgres;Password=postgres
  ConnectionStrings__NotificationDb: Host=notification-db;Port=5432;Database=notifications;Username=postgres;Password=postgres
  ConnectionStrings__WorkflowDb: Host=workflow-db;Port=5432;Database=workflows;Username=postgres;Password=postgres
